name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: |
          cd C:\Users\a\Desktop\IOT_GateWay
          git pull origin main

      - name: Restart PM2
        run: pm2 restart iot-gateway